/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    Feedback: typeof import('./src/components/feedback/index.vue')['default']
    GithubCorner: typeof import('./src/components/github-corner/index.vue')['default']
    LazyloadImage: typeof import('./src/components/lazyload-image/index.vue')['default']
    Search: typeof import('./src/components/search/index.vue')['default']
  }
}
