title: 有趣网站
icon: fa-gamepad
subMenu:
  - title: 随机跳转
    links:
      - title: 十年之约
        description: 虫洞-随机访问十年之约成员的网站
        url: https://www.foreverblog.cn/go.html
        logo: ""
      - title: 开往
        description: 开往-友链接力
        url: https://travellings.link/
        logo: ""
  - title: 音乐相关
    links:
      - title: radio在线听
        description: 在线聆听世界各个国家不同时代的歌曲
        url: https://radiooooo.com
        logo: ""
  - title: 地图相关
    links:
      - title: 有趣街景
        description: 随机有趣的谷歌街景
        url: https://neal.fun/wonders-of-street-view/
        logo: ""
